language: php

php:
    - 5.4
    - 5.5
    - 5.6

env:
    - DB=mysql

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - mkdir -p build/logs
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS `doll`; CREATE DATABASE `doll`;'; FI"

script:
    - phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v